apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: dineshsonawanereactsampleapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dineshsonawanereactsampleapp 
    spec:
      containers:
        - name: dineshsonawanereactsampleapp 
          image: aksacrpi.azurecr.io/dineshsonawanereactsampleapp
          ports:
          - containerPort: 80